version: "3.14"

services:
  postgres:
    image: postgres:18
    container_name: loose_papers_pg
    environment:
      POSTGRES_DB: loose_papers
      POSTGRES_USER: loose
      POSTGRES_PASSWORD: loose
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: loose_papers_redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
